spring:
  application:
    name: app-manager

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/app_manager_db}
    username: ${DB_USERNAME:app_manager}
    password: ${DB_PASSWORD:app_manager}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: appmanageradm@gmail.com
    password: jwfmmbeospwrovmz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: ${PORT:8090}
  servlet:
    context-path: /app-manager/v1

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}