spring:
  application:
    name: app-manager

  datasource:
    url: jdbc:mysql://localhost:3306/app_manager_db
    username: app_manager
    password: app_manager

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8090
  servlet:
    context-path: /app-manager/v1