spring:
  application:
    name: app-manager

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/app_manager_db}
    username: ${DB_USERNAME:app_manager}
    password: ${DB_PASSWORD:app_manager}
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10           # Máximo de conexões simultâneas
      minimum-idle: 2                 # Mínimo de conexões ociosas
      idle-timeout: 600000            # Tempo máximo de inatividade (ms)
      connection-timeout: 30000       # Tempo limite para obter uma conexão (ms)
      max-lifetime: 1800000           # Tempo máximo de vida de uma conexão (ms)
      leak-detection-threshold: 20000 # Detecta conexões não liberadas (ms)
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_SECRET}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000



server:
  port: ${PORT:8090}
  servlet:
    context-path: /app-manager/v1
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

stackhero:
  s3:
    access-key: ${AH_S3_OBJECT_STORAGE_STACKHERO_CYAN_ROOT_ACCESS_KEY}
    secret-key: ${AH_S3_OBJECT_STORAGE_STACKHERO_CYAN_ROOT_SECRET_KEY}
    endpoint: ${AH_S3_OBJECT_STORAGE_STACKHERO_CYAN_HOST}
    bucket: ${BUCKET}
    region: auto