spring:
  application:
    name: app-manager

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8090
  servlet:
    context-path: /app-manager/v1

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}